### ISSUE TITLE
Should the alien crew member outfits be installable?

### ISSUE THREAD

**Issue by Alkallid** [Disiuze/alphean-expansion#8]
In boarding, you kill all opposing crew, so you can't use them again when you capture. You could say you capture them so they're usable, but it'd be non-canon or your crew would be alien beta-DNA-enhanced or whatever.

**Comment by Disiuze** [comment]
That's an issue I've thought about many times but I had no idea how to make it properly. I might add an installable -1 attribute but that still allows usage if you just don't uninstall them.
As far as I know, this is only really a problem for boarding, 'buying' the crew member to work on your ship.

**Comment by Alkallid** [comment]
It's especially bizarre if you cap a minimum crewed ship, as when you 'fill it up', where do those extra aliens come from, even if you enslaved them all?

**Comment by Amazinite** [comment]
They shouldn't exist. :3
